const AuthenticatorAttestationResponse = require('../../main/nodejs/AuthenticatorAttestationResponse');

const attStr = {
  "response":{
    "clientDataJSON":"eyJjaGFsbGVuZ2UiOiJBNkxuekZucXZhR3d1VUplbFpzcUwzYWpULWZlNEVILV90cnVIZm8zZ3IwIiwib3JpZ2luIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwidG9rZW5CaW5kaW5nIjoidW51c2VkIiwidHlwZSI6IndlYmF1dGhuLmNyZWF0ZSJ9",
    "attestationObject":"o2NmbXRoZmlkby11MmZnYXR0U3RtdKJjc2lnWEgwRgIhAKDkMFyD/MOOJuvtdTKMpMU1gCDmVPlnI9flLA1bkHCKAiEAnhJwKzWWa4Iv6iD47uMvEufqxVfX2IrLS+EGiPRcTdxjeDVjgVkBKjCCASYwgcygAwIBAgIBATAKBggqhkjOPQQDAjAOMQwwCgYDVQQDEwNVMkYwIhgPMjAwMDAxMDEwMDAwMDBaGA8yMDk5MTIzMTIzNTk1OVowDjEMMAoGA1UEAxMDVTJGMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE//oBOvQLbhvBfmnOt7vGVIzTrjLNj3RF6Qe51YaMK6MJ09sA62TKEa6eeeDVZ2S3yiOVaSV0TEZkNW+Q6Fi0k6MXMBUwEwYLKwYBBAGC5RwCAQEEBAMCBSAwCgYIKoZIzj0EAwIDSQAwRgIhAJJNwsg1oeUgUrGI5mMJTBFZC3kSnDL68NW5iBvhMIG0AiEA5yZjTOnJGaBqQZ+LutnLeKZCiefc9GNzzZ09Y5oupspoYXV0aERhdGFYxEmWDeWIDoxodDQXD2R2YFuP5K65ooYyx5lc87qDHZdjQQAAAAAAAAAAAAAAAAAAAAAAAAAAAEBI9h8/86ifSy+QpVJkOPuJhaZ7cRZouklRtj7gvTl++B6CkY8vkOgOktR5B7S6e/DRIUM7g+UWB7tvwm/m17OPpQECAyYgASFYIP/6ATr0C24bwX5pzre7xlSM064yzY90RekHudWGjCujIlggCdPbAOtkyhGunnng1Wdkt8ojlWkldExGZDVvkOhYtJM="
    }
  }
const attObj = new AuthenticatorAttestationResponse(attStr.response);
console.log(attObj);